export const Data = [
  {
    id: 1,
    images: ["https://shorturl.at/voHyB"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: true,
  },
  {
    id: 2,
    images: ["https://shorturl.at/8nTpE"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 3,
    images: ["https://shorturl.at/voHyB"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 4,
    images: ["https://shorturl.at/8nTpE"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 5,
    images: [
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 6,
    images: [
      "https://shorturl.at/8nTpE",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 7,
    images: [
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 8,
    images: ["https://shorturl.at/8nTpE"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 9,
    images: ["https://shorturl.at/voHyB"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 10,
    images: ["https://shorturl.at/8nTpE"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 12,
    images: ["https://shorturl.at/voHyB"],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 13,
    images: [
      "https://shorturl.at/8nTpE",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 14,
    images: [
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 15,
    images: [
      "https://shorturl.at/8nTpE",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 16,
    images: [
      "https://shorturl.at/02uyS",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 17,
    images: [
      "https://shorturl.at/02uyS",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 18,
    images: [
      "https://shorturl.at/02uyS",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 19,
    images: [
      "https://shorturl.at/02uyS",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 20,
    images: [
      "https://shorturl.at/02uyS",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 21,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 22,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 23,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 24,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 25,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 26,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 27,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 28,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 29,
    images: [
      "https://shorturl.at/02uyS",

      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
  {
    id: 30,
    images: [
      "https://shorturl.at/02uyS",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/voHyB",
      "https://shorturl.at/WlCnu",
    ],
    pieces: 26,
    rating: 3.4,
    title: "Beautiful and picturesque 2 sto...",
    gps: "12 Morris Ave, Toronto, ON, CA,",
    guests: 2,
    isNew: false,
  },
];
